# Generated by Django 5.1.4 on 2026-05-17 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.PositiveSmallIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=16)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['property', 'check_in', 'check_out'], name='bookings_bo_propert_b6e6e3_idx'), models.Index(fields=['user', '-created_at'], name='bookings_bo_user_id_6151bb_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_in__lt', models.F('check_out'))), name='bk_check_in_before_check_out'), models.CheckConstraint(condition=models.Q(('guests__gt', 0)), name='bk_guests_positive'), models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='bk_total_non_negative')],
            },
        ),
    ]
