# Generated by Django 5.1.4 on 2026-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_partial_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='language',
            field=models.CharField(default='es', max_length=2),
        ),
    ]
